### ISSUE TITLE
Default host is tux.

### ISSUE THREAD

**Issue by aitet** [gergap/vim-ollama#1]
Why is the default ollama_host = 'http://tux:11434'? instead of localhost or preferably 127.0.0.1.

The read me says:
Variable	Default	Description
g:ollama_host	http://localhost:11434	The URL of the Ollama server.

So i was confused when it didn't work until I looked inside the file and changed ollama_host.

**Comment by gergap** [comment]
Thanks for reporting this issue. I accidentally commited this test address.
Fixed it already.
