### ISSUE TITLE
Pressing tab automatically outputs text

### ISSUE THREAD

**Issue by hendawy** [gergap/vim-ollama#12]
For some reason pressing tab always output text
![Screenshot 2024-12-16 at 17 47 45](https://github.com/user-attachments/assets/a7f50367-0f50-459a-ac7d-2508b012f2ec)

**Comment by quimey** [comment]
I have the same problem, did you find a solution?

**Comment by gergap** [comment]
please post your Vim version and tab mapping without vim-ollama loaded, so that I can try to reproduce it.
Use this command to get the activate tab mapping in insert mode.
`:imap <tab>`

**Comment by quimey** [comment]
@gergap it was solved in the latest version. Thanks
