### ISSUE TITLE
Tab and Chat error

### ISSUE THREAD

**Issue by MarvAmBass** [gergap/vim-ollama#2]
Hi there,

thanks for creating this plugin - unfortunately I have two issues (macos - might be releated, but my other vim plugins work):

My testfile:

```
#!/usr/bin/env python3
# Create a game for guessing a number between 1 and 100.
```

1. Chat error:

Once I load the chat and ask something I get the following error message:

```
An error occurred: Attempted to access streaming response content, without having called `read()`.
```

`ollama serve` logs:

```
[GIN] 2024/10/13 - 20:04:29 | 404 |    4.296125ms |       127.0.0.1 | POST     "/api/chat"
```

Update 1: I noticed that `requests` was missing as well for the `ollama.py` so I installed that as well, but still got the same error.

2. Tab error

This might be a user error from my side, but I'm not sure.

Once I press tab, I get the following error message in the command line. Is there a plugin I'm missing? Some kind of dependency. 

```
E15: Invalid expression: "<Plug>(ollama-tab-completion)"
```

`ollama serve` logs:

```
[GIN] 2024/10/13 - 20:26:39 | 500 |  2.604134458s |       127.0.0.1 | POST     "/api/generate"
```

I ensured the model is downloaded and checked if ollama run <modelname> and there it would autocomplete my 2 lines

3. General questions

Are there some dependencies needed? I read your readme and didn't find much to prepare. I noticed that the chat python needs `httpx` which I installed, but other than that it should work out of box - am I right?

Thanks and Kinds regards

Marvin

**Comment by gergap** [comment]
Hi,

you can first try to test the python script on the shell to see if it works:
```
$> cd ~/.vim/plugged/vim-ollama/python
$> ./chat.py -m llama3.2 -u http://localhost:11434
hi
How can I assist you today?<EOT>
write a python hello world
Here is a simple "Hello, World!" program in Python:

` ` `python
# This is a comment - anything after the "#" symbol is ignored by the interpreter.

print("Hello, World!")
 ` ` `

If you want to save it as a file, let's say `hello.py`, here's how you can do it:

1. Open a text editor (like Notepad or TextEdit) and create a new file.
2. Copy and paste the above code into the file.
3. Save the file with a `.py` extension (e.g., `hello.py`).

Then, open your command line or terminal and navigate to the directory where you saved the file.

4. Type `python hello.py` to run the program.

You should see "Hello, World!" printed out on the screen!<EOT>
/bye
Exiting the chat.
```
Adapt model and url arguments to your needs. If it works it should work in Vim too, otherwise python will show an exception. Probably some python deps are just missing. See the import statements in the script and install them using `pip3 install <package>`.

From what I know only httpx needs to be installed, everything else is part of python. But I did not test MacOS, because I'm working on Linux.

Hope this helps fixing the issue.

**Comment by gergap** [comment]
`<Plug>` mappings require at least Vim 6.0.

**Comment by MarvAmBass** [comment]
thanks for your fast reply, my macos has a vim 9.0, so this should be fine.

python also works, but I guess my dependencies are broken, I installed everything in a venv and the python scripts themself throw errors. I might find time to debug them tomorrow. And I'll also try everything on a linux machine - if it works out of box and I get it to work on macos I might improve your readme for other macos users

thanks and have a nice day

Marvin

**Comment by MarvAmBass** [comment]
this is the error message I get when working with your `chat.py`

```
 python3 ~/.vim/plugged/vim-ollama/python/chat.py -m llama3.2 -u http://localhost:11434
test
An error occurred: Attempted to access streaming response content, without having called `read()`.
test
An error occurred: Attempted to access streaming response content, without having called `read()`.
```

ollama logs:

```

[GIN] 2024/10/13 - 21:28:37 | 404 |     362.959µs |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/10/13 - 21:28:39 | 404 |     709.459µs |       127.0.0.1 | POST     "/api/chat"

```

something is broken here - do you use the latest `httpx` library? I'd guess that this streaming response error is part of `httpx`

**Comment by MarvAmBass** [comment]
okay I just checked the whole plugin with my ubuntu machine - exactly the same problem.

Chat answers with: `An error occurred: Attempted to access streaming response content, without having called `read()`.
`

Is there a way to test ollama.py via python3 - It seems I can write endlessly and it won't trigger the api

this are my installed python3 packages

most important are:
```
python3-httpx               0.26.0-2
python3-requests            2.31.0+dfsg-1ubuntu1 
```

```
dpkg --list | grep python3-
ii  libpython3-stdlib:arm64     3.12.3-0ubuntu2                   arm64        interactive high-level object-oriented language (default python3 version)
ii  python3-anyio               4.2.0-1                           all          Asynchronous compatibility layer (Python 3)
ii  python3-certifi             2023.11.17-1                      all          root certificates for validating SSL certs and verifying TLS hosts (python3)
ii  python3-chardet             5.2.0+dfsg-1                      all          Universal Character Encoding Detector (Python3)
ii  python3-click               8.1.6-2                           all          Wrapper around optparse for command line utilities - Python 3.x
ii  python3-colorama            0.4.6-4                           all          Cross-platform colored terminal text in Python - Python 3.x
ii  python3-h11                 0.14.0-1                          all          Pure-Python, bring-your-own-I/O implementation of HTTP/1.1 (Python 3)
ii  python3-httpcore            1.0.2-2                           all          minimal low-level HTTP client
ii  python3-httpx               0.26.0-2                          all          next generation HTTP client
ii  python3-idna                3.6-2ubuntu0.1                    all          Python IDNA2008 (RFC 5891) handling (Python 3)
ii  python3-markdown-it         3.0.0-2                           all          Python port of markdown-it and some its associated plugins
ii  python3-mdurl               0.1.2-1                           all          Python port of the JavaScript mdurl package
ii  python3-minimal             3.12.3-0ubuntu2                   arm64        minimal subset of the Python language (default python3 version)
ii  python3-pkg-resources       68.1.2-2ubuntu1.1                 all          Package Discovery and Resource Access using pkg_resources
ii  python3-pygments            2.17.2+dfsg-1                     all          syntax highlighting package written in Python 3
ii  python3-requests            2.31.0+dfsg-1ubuntu1              all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-rich                13.7.1-1                          all          render rich text, tables, progress bars, syntax highlighting, markdown and more
ii  python3-sniffio             1.3.0-2                           all          detect which async Python library is in use (Python3 version)
ii  python3-urllib3             2.0.7-1                           all          HTTP library with thread-safe connection pooling for Python3
```

**Comment by MarvAmBass** [comment]
I noticed that the pip packages are newer, so I uninstalled the ubuntu packages, used autoremove to clean dependencies and used pip to install httpx and requests, still the same errors

can you check which versions you have installed? I bet there is some difference in the versions

**Comment by gergap** [comment]
Hi, I have 
```
python3-httpx/stable,stable,now 0.23.3-1 all  [Installiert,automatisch]
  next generation HTTP client
```
Installed via apt from Debian. Works on all my machines, but they are all Debian.

**Comment by gergap** [comment]
Have you checked that ollama is running on the given host:port number?
The python code can be improved for sure, but first we should check if the error is really caused by python or it is a real error. You can check also using Wireshark if there is a working communication and you get a response from ollama.

**Comment by MarvAmBass** [comment]
Ohhh perfect, thank you - debian was the answer! (they are always a bit behind when it comes to packaged versions)

so now on debian it seems to work (vim version 9.0), but this tab error still occurs (although it worked once):

```
E15: Invalid expression: "<Plug>(ollama-tab-completion)"
```

chat still seems to be buggy:
```
Chat with Bot                                                                                        
-------------                                                                                        
>>> is this working?                                                                                  
An error occurred: Attempted to access streaming response content, without having called `read()`. 
```

manual python call of chat
```
python3 ~/.vim/plugged/vim-ollama/python/chat.py -m llama3.2 -u http://127.0.0.1:11434
test
An error occurred: Attempted to access streaming response content, without having called `read()`.
```

**Comment by bdrewery** [comment]
I get the tab error too with vim 9.1. I had to do this as a workaround to get it to work after the first tab.
```
diff --git plugin/ollama.vim plugin/ollama.vim
index f1eb8e4..f11a6f0 100644
--- plugin/ollama.vim
+++ plugin/ollama.vim
@@ -45,7 +45,7 @@ function! s:HandleTabCompletion() abort
         " return AI suggestion
         return suggestion
     endif
-    if !empty(b:ollama_original_tab_mapping)
+    if 0 && !empty(b:ollama_original_tab_mapping)
         " If no completion and there is an original <Tab> mapping, execute it
         return "\<C-R>=" . b:ollama_original_tab_mapping . "\<CR>"
     else

```

**Comment by MarvAmBass** [comment]
thanks so much @bdrewery - this fixed my issue with the tab error!

**Comment by gergap** [comment]
Interesting, the idea is that when you have mapped tab to something like e.g. YCM or CoC, that the plugin calls this original mapping if there is no AI completion. It is also checked to not be empty to avoid such errors. Your "fix" disables this fallback completely. Can you tell me what the tab mapping looks like in your config when you don't load the vim-ollama plugin?
`imap <tab>`

**Comment by MarvAmBass** [comment]
that's also what I noticed, but I test your plugin on fresh installs right now - so there are no other tab completion plugins in place for now.

Right now I just try to get it to run without errors, until i try to migrate everything to my main setup

interestingly I still haven't found a solution for the `read()` issue - the code seems to be fine, and I tried different versions of the `httpx` library.

**Comment by MarvAmBass** [comment]
all errors vanished after I updated ollama and made sure that the models are loaded.

I debugged using a bare minimum python script which was triggering ollamas API script until it worked.

I also reveresed the vim script fix for the tab completion, and it worked without the error reoccuring.

thanks for the plugin! looking forward to play around with it :)

**Comment by bdrewery** [comment]
@gergap 

> Interesting, the idea is that when you have mapped tab to something like e.g. YCM or CoC, that the plugin calls this original mapping if there is no AI completion. It is also checked to not be empty to avoid such errors. Your "fix" disables this fallback completely. Can you tell me what the tab mapping looks like in your config when you don't load the vim-ollama plugin? `imap <tab>`

The intent makes sense. I disabled other Tab mappings when I first hit the error but it wasn't enough

My "fix" is not a fix. It just avoids an error and an excess tab lands after the completion too.
````
:imap <Tab>
No mapping found
```

Perhaps this should be a separate issue if you're willing to dig into it.

**Comment by gergap** [comment]
@bdrewery yes, please open a new issue for that.
I digged already into to it and have a potential fix on branch fix_empty_tab_mapping_issue
