### ISSUE TITLE
Feature Request: Allow to set options for ollama request

### ISSUE THREAD

**Issue by MarvAmBass** [gergap/vim-ollama#3]
I noticed, that the generation is lagging on my M1 Macbook.

To improve performance I hardcoded a `num_predict` into the `python/ollama.py`file

```
    data = {
        'model': model,
        'prompt': prompt,
        'stream': False,
        'options': {
            'temperature': 0,
            'top_p': 0.95,
            'num_predict': 256
        }
    }
```

There might be also other users with different option requirements - but I'm not sure what's the best way to configure those values.

My gut feeling tells me to put the options into the `~/vimrc` and parse it from the python script - I wouldn't want another additional cli parameter and pass it from the vimrc via vimscript to python...

what do you think?

**Comment by gergap** [comment]
should be easy to add new commandline options and set them in .vimrc.
I'll try that and create a new feature branch for it.

**Comment by gergap** [comment]
you can try out the ollama_options branch now

**Comment by MarvAmBass** [comment]
thanks so much! you already implemented it - ahhh you used the python options. makes sense I guess, so it stays consistent with the other options!
