### ISSUE TITLE
Weird Tab issue

### ISSUE THREAD

**Issue by bdrewery** [gergap/vim-ollama#6]
I get `<t_ý>S(ollama-tab-completion)` when using tab after the first insert. I must have missed that when testing #4  before.

Hexdump of this data;
```
00000000  3c 74 5f c3 bd 3e 53 28  6f 6c 6c 61 6d 61 2d 74  |<t_..>S(ollama-t|
00000010  61 62 2d 63 6f 6d 70 6c  65 74 69 6f 6e 29 0a     |ab-completion).|
0000001f
```

`:imap` in this state:
```
i  <Plug>(ollama-tab-completion) * <C-R>=<SNR>52_HandleTabCompletion()<CR>
...
i  <Tab>         <Plug>(ollama-tab-completion)
```

https://stackoverflow.com/questions/34487155/plug-function-failing-inserting-as-literal-t-%c3%bds talks about this odd literal showing up.

**Comment by gergap** [comment]
Yes, I noticed already the same issue. The tab handling is really harder to implement then anticipated, but I will look into this issue ASAP.

**Comment by bdrewery** [comment]
I still get `<t_ý>S(ollama-tab-completion)` when using tab on 68830e349814b6c16f4c51bfbad59e9b4bded023

**Comment by bdrewery** [comment]
If you got an email - I edited. The problem I get now is when vim-ollama is not configured.
