### ISSUE TITLE
`httpx` module missing

### ISSUE THREAD

**Issue by jjasghar** [gergap/vim-ollama#8]
I'm attempting to run this on my Mac with a homebrew-installed version of Python.

It seems `httpx` is a requirement, and I can't seem to get my virtual environment installed version of httpx to have the `chat.py` point to it.

I'm running python 3.11 also, is that ok? What am I missing?

**Comment by jjasghar** [comment]
I was bad and went ahead and did:
```
/usr/bin/env pip3 install httpx --break-system-packages
```

And it seems to be working. But I don'tk know if that's a good fix :shrug:

You can close this if you'd like it may help someone in the future.

**Comment by corrosive4354** [comment]
Although httpx is successfully installed, this method is not the best practice. Using the --break-system-packages option may cause confusion in system package management, especially when using Homebrew to install Python.

I think you can try the [servbay](https://servbay.com) tool, which is more professional on Mac and supports more than homebrew.

**Comment by lrvl** [comment]
On Debian and AlmaLinux it was just adding the distro package

**Comment by gergap** [comment]
I updated the README.md with a Requirements sections. Hope this helps other users with the same problem.

**Comment by lobiCode** [comment]
Hi,
I'm encountering an error when trying to use the :OllamaChat command in the vim-ollama plugin. The chat process terminates with the following error:

```
Chat process terminated with exit code 1
Use.С ':q!' or ':bd!' to delete this buffer and run ':OllamaChat' again to create a new session.
Traceback (most recent call last):
  File "~/.vim/pack/plugins/start/vim-ollama/python/chat.py", line 9, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

```
```
~ $ apt policy python3-httpx
python3-httpx:
  Installed: 0.26.0-2
  Candidate: 0.26.0-2
  Version table:
 *** 0.26.0-2 500
        500 http://si.archive.ubuntu.com/ubuntu oracular/universe amd64 Packages
        100 /var/lib/dpkg/status
```
